-- ============================================================
-- 公司管理系統 — Supabase 資料庫初始化腳本
-- 使用方式：登入 Supabase 專案 → 左側選單「SQL Editor」→
--           貼上這整份檔案的內容 → 按「Run」執行一次即可。
-- ============================================================

-- 1) 通用鍵值儲存表
--    App 內每個模組（員工、打卡、薪資、估價單…）都存成一筆
--    storage_key + value(jsonb) 的資料，維持跟原本 Claude Artifact
--    版本一樣的資料結構，方便前端程式碼幾乎不用大改。
create table if not exists app_storage (
  id uuid primary key default gen_random_uuid(),
  storage_key text unique not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table app_storage enable row level security;

-- 任何「已登入」的公司帳號都可以讀取全部資料（因為是全公司共用一份帳本）
drop policy if exists "authenticated can read app_storage" on app_storage;
create policy "authenticated can read app_storage"
  on app_storage for select
  to authenticated
  using (true);

-- 任何「已登入」的公司帳號都可以新增／更新資料
drop policy if exists "authenticated can upsert app_storage" on app_storage;
create policy "authenticated can upsert app_storage"
  on app_storage for insert
  to authenticated
  with check (true);

drop policy if exists "authenticated can update app_storage" on app_storage;
create policy "authenticated can update app_storage"
  on app_storage for update
  to authenticated
  using (true);

-- 把這張表加進 Supabase 的即時推播（Realtime）發布清單，這樣某個人新增／修改任何模組的資料時，
-- 其他人畫面上的清單會自動更新，不用手動重新整理；用 DO 區塊包起來判斷是否已經加過，
-- 這樣整份 SQL 重複執行也不會噴錯。
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'app_storage'
  ) then
    alter publication supabase_realtime add table app_storage;
  end if;
end $$;

-- 1-1) 清單型資料改成「一筆資料一列」
--      app_records 保存每筆資料；app_collection_versions 保存各清單版本。
--      網站每次儲存都必須帶入讀取時的版本，若其他人已先更新，資料庫會拒絕
--      舊版本覆蓋，讓前端重新載入最新內容。
create table if not exists app_collection_versions (
  collection_key text primary key,
  version bigint not null default 0 check (version >= 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists app_records (
  collection_key text not null references app_collection_versions(collection_key) on delete cascade,
  record_id text not null,
  value jsonb not null check (jsonb_typeof(value) = 'object'),
  sort_order integer not null default 0,
  record_version bigint not null default 1 check (record_version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (collection_key, record_id)
);

create index if not exists app_records_collection_order_idx
  on app_records (collection_key, sort_order, record_id);
create index if not exists app_collection_versions_updated_by_idx
  on app_collection_versions (updated_by) where updated_by is not null;
create index if not exists app_records_updated_by_idx
  on app_records (updated_by) where updated_by is not null;

-- 每筆異動保留歷史快照。這張表不開放給網站直接讀寫，僅供管理員備援還原。
create table if not exists app_record_history (
  history_id bigint generated by default as identity primary key,
  collection_key text not null,
  record_id text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  value jsonb not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null
);

create index if not exists app_record_history_lookup_idx
  on app_record_history (collection_key, record_id, changed_at desc);
create index if not exists app_record_history_changed_by_idx
  on app_record_history (changed_by) where changed_by is not null;

-- 只在第一次建立逐筆資料層時，從 app_storage 的最新資料搬入；重複執行不會
-- 用舊 JSON 覆蓋已經切換完成的逐筆資料。
with collection_keys(collection_key) as (
  values
    ('employees'), ('attendance'), ('payroll'), ('quotations'),
    ('invoices'), ('billing'), ('accounting'), ('vendors'),
    ('official_documents'), ('document_templates'), ('contracts'), ('sys_users'),
    ('quote_templates'), ('vehicles'), ('contract_billing_tracking'), ('leave_requests')
), to_migrate as (
  select s.storage_key as collection_key, s.value, s.updated_at
  from app_storage s
  join collection_keys k on k.collection_key = s.storage_key
  left join app_collection_versions v on v.collection_key = s.storage_key
  where v.collection_key is null and jsonb_typeof(s.value) = 'array'
)
insert into app_collection_versions (collection_key, version, updated_at)
select collection_key, 1, updated_at
from to_migrate
on conflict (collection_key) do nothing;

with collection_keys(collection_key) as (
  values
    ('employees'), ('attendance'), ('payroll'), ('quotations'),
    ('invoices'), ('billing'), ('accounting'), ('vendors'),
    ('official_documents'), ('document_templates'), ('contracts'), ('sys_users'),
    ('quote_templates'), ('vehicles'), ('contract_billing_tracking'), ('leave_requests')
)
insert into app_collection_versions (collection_key, version)
select collection_key, 0 from collection_keys
on conflict (collection_key) do nothing;

-- 從舊 JSON 搬資料時，只處理逐筆資料表仍為空的集合；每筆既有資料都有 id。
insert into app_records (
  collection_key, record_id, value, sort_order, record_version, created_at, updated_at
)
select
  s.storage_key,
  elem->>'id',
  elem,
  (ord - 1)::integer,
  1,
  s.updated_at,
  s.updated_at
from app_storage s
cross join lateral jsonb_array_elements(s.value) with ordinality as records(elem, ord)
join app_collection_versions migrated
  on migrated.collection_key = s.storage_key
 and migrated.version = 1
 and migrated.updated_at = s.updated_at
where s.storage_key in (
  'employees', 'attendance', 'payroll', 'quotations', 'invoices', 'billing',
  'accounting', 'vendors', 'official_documents', 'document_templates', 'contracts',
  'sys_users', 'quote_templates', 'vehicles', 'contract_billing_tracking', 'leave_requests'
)
  and jsonb_typeof(s.value) = 'array'
  and nullif(elem->>'id', '') is not null
  and not exists (
    select 1 from app_records existing
    where existing.collection_key = s.storage_key
  )
on conflict (collection_key, record_id) do nothing;

create or replace function public.log_app_record_change()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if tg_op = 'INSERT' then
    insert into public.app_record_history
      (collection_key, record_id, operation, value, changed_by)
    values
      (new.collection_key, new.record_id, tg_op, new.value, new.updated_by);
    return new;
  elsif tg_op = 'UPDATE' then
    if old.value is distinct from new.value then
      insert into public.app_record_history
        (collection_key, record_id, operation, value, changed_by)
      values
        (old.collection_key, old.record_id, tg_op, old.value, new.updated_by);
    end if;
    return new;
  else
    insert into public.app_record_history
      (collection_key, record_id, operation, value, changed_by)
    values
      (old.collection_key, old.record_id, tg_op, old.value, old.updated_by);
    return old;
  end if;
end
$function$;

drop trigger if exists app_records_history_trigger on app_records;
create trigger app_records_history_trigger
after insert or update or delete on app_records
for each row execute function public.log_app_record_change();

-- 以單一資料庫交易完成整份清單的逐筆新增／修改／刪除。
-- SECURITY DEFINER 僅用來強制所有寫入都經過版本檢查；函式會驗證登入狀態、
-- 限制既有集合，且下方撤銷 PUBLIC／anon 權限，只開放 authenticated 呼叫。
create or replace function public.save_app_collection(
  p_collection_key text,
  p_expected_version bigint,
  p_records jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  current_version bigint;
  next_version bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if jsonb_typeof(p_records) is distinct from 'array' then
    raise exception 'p_records must be a JSON array' using errcode = '22023';
  end if;

  select version into current_version
  from public.app_collection_versions
  where collection_key = p_collection_key
  for update;

  if not found then
    raise exception 'Unknown collection key' using errcode = '22023';
  end if;
  if current_version <> p_expected_version then
    return jsonb_build_object('success', false, 'version', current_version);
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_records) elem
    where jsonb_typeof(elem) <> 'object' or nullif(elem->>'id', '') is null
  ) then
    raise exception 'Every record must be an object with a non-empty id' using errcode = '22023';
  end if;
  if exists (
    select elem->>'id'
    from jsonb_array_elements(p_records) elem
    group by elem->>'id'
    having count(*) > 1
  ) then
    raise exception 'Duplicate record id' using errcode = '22023';
  end if;

  insert into public.app_records (
    collection_key, record_id, value, sort_order, record_version,
    created_at, updated_at, updated_by
  )
  select
    p_collection_key,
    elem->>'id',
    elem,
    (ord - 1)::integer,
    1,
    now(),
    now(),
    auth.uid()
  from jsonb_array_elements(p_records) with ordinality as incoming(elem, ord)
  on conflict (collection_key, record_id) do update
  set
    value = excluded.value,
    sort_order = excluded.sort_order,
    record_version = case
      when app_records.value is distinct from excluded.value
        then app_records.record_version + 1
      else app_records.record_version
    end,
    updated_at = now(),
    updated_by = auth.uid()
  where app_records.value is distinct from excluded.value
     or app_records.sort_order is distinct from excluded.sort_order;

  delete from public.app_records existing
  where existing.collection_key = p_collection_key
    and not exists (
      select 1
      from jsonb_array_elements(p_records) elem
      where elem->>'id' = existing.record_id
    );

  next_version := current_version + 1;
  update public.app_collection_versions
  set version = next_version, updated_at = now(), updated_by = auth.uid()
  where collection_key = p_collection_key;

  return jsonb_build_object('success', true, 'version', next_version);
end
$function$;

alter table app_collection_versions enable row level security;
alter table app_records enable row level security;
alter table app_record_history enable row level security;

drop policy if exists "authenticated can read app collection versions" on app_collection_versions;
create policy "authenticated can read app collection versions"
  on app_collection_versions for select
  to authenticated
  using (true);

drop policy if exists "authenticated can read app records" on app_records;
create policy "authenticated can read app records"
  on app_records for select
  to authenticated
  using (true);

drop policy if exists "clients cannot read app record history" on app_record_history;
create policy "clients cannot read app record history"
  on app_record_history for select
  to authenticated
  using (false);

revoke all on app_collection_versions from public, anon, authenticated;
revoke all on app_records from public, anon, authenticated;
revoke all on app_record_history from public, anon, authenticated;
grant select on app_collection_versions, app_records to authenticated;
grant select, insert, update, delete on app_collection_versions, app_records, app_record_history to service_role;

revoke all on function public.save_app_collection(text, bigint, jsonb) from public, anon;
grant execute on function public.save_app_collection(text, bigint, jsonb) to authenticated, service_role;
revoke all on function public.log_app_record_change() from public, anon, authenticated;

-- 舊 app_storage 的 JSON 清單保留作為唯讀回復點；設定型資料仍可正常更新。
drop policy if exists "authenticated can upsert app_storage" on app_storage;
drop policy if exists "authenticated can upsert scalar app_storage" on app_storage;
create policy "authenticated can upsert scalar app_storage"
  on app_storage for insert
  to authenticated
  with check (jsonb_typeof(value) <> 'array');

drop policy if exists "authenticated can update app_storage" on app_storage;
drop policy if exists "authenticated can update scalar app_storage" on app_storage;
create policy "authenticated can update scalar app_storage"
  on app_storage for update
  to authenticated
  using (jsonb_typeof(value) <> 'array')
  with check (jsonb_typeof(value) <> 'array');

-- Realtime 只需監聽集合版本；版本改變時，網站會重新讀取該集合的逐筆資料。
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'app_collection_versions'
  ) then
    alter publication supabase_realtime add table app_collection_versions;
  end if;
end $$;

notify pgrst, 'reload schema';

-- 2) 估價單附件（掃描檔圖片）Storage bucket
--    每張估價單可以上傳掃描檔圖片保存，實際檔案存在 Supabase Storage，
--    估價單資料裡只存檔案路徑（見 app_storage 的 quotations）。
--    bucket 設為非公開，只有登入的公司帳號能讀取／上傳／刪除，
--    讀取時前端會用 createSignedUrl() 產生一組限時的預覽網址。
insert into storage.buckets (id, name, public)
values ('quote-scans', 'quote-scans', false)
on conflict (id) do nothing;

-- 確保 bucket 允許上傳圖片、PDF 與 Word 公文範本（.doc／.docx）（如果 bucket 已存在、
-- 且之前在 Dashboard 上被設成只允許圖片類型，上面的 insert 不會更新既有設定，
-- 所以這裡另外強制更新一次）
update storage.buckets
set allowed_mime_types = array['image/png','image/jpeg','image/jpg','image/gif','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword']
where id = 'quote-scans';

drop policy if exists "authenticated can read quote-scans" on storage.objects;
create policy "authenticated can read quote-scans"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'quote-scans');

drop policy if exists "authenticated can upload quote-scans" on storage.objects;
create policy "authenticated can upload quote-scans"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'quote-scans');

drop policy if exists "authenticated can delete quote-scans" on storage.objects;
create policy "authenticated can delete quote-scans"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'quote-scans');

-- 3) 內部即時通訊（系統帳號之間一對一聊天，右下角對話框功能）
create table if not exists chat_messages (
  id uuid primary key default gen_random_uuid(),
  sender_id text not null,
  recipient_id text not null,
  content text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists chat_messages_sender_idx on chat_messages (sender_id, created_at);
create index if not exists chat_messages_recipient_idx on chat_messages (recipient_id, created_at);

alter table chat_messages enable row level security;

drop policy if exists "authenticated can read chat_messages" on chat_messages;
create policy "authenticated can read chat_messages"
  on chat_messages for select
  to authenticated
  using (true);

drop policy if exists "authenticated can insert chat_messages" on chat_messages;
create policy "authenticated can insert chat_messages"
  on chat_messages for insert
  to authenticated
  with check (true);

drop policy if exists "authenticated can update chat_messages" on chat_messages;
create policy "authenticated can update chat_messages"
  on chat_messages for update
  to authenticated
  using (true);

-- 把這張表加進 Supabase 的即時推播（Realtime）發布清單，
-- 對話框才能不重新整理就馬上收到新訊息；用 DO 區塊包起來
-- 判斷是否已經加過，這樣整份 SQL 重複執行也不會噴錯。
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table chat_messages;
  end if;
end $$;

-- ============================================================
-- 重要提醒（請務必閱讀）
-- ============================================================
-- 上面的 RLS 規則只做到「必須登入才能讀寫」這一層安全防護，
-- 並沒有做到「一般員工只能改自己的打卡紀錄」這種更細緻的資料庫層級管控——
-- 因為目前每個模組的資料是整包存成一個 JSON（例如所有人的打卡紀錄
-- 全部放在同一個 storage_key = 'attendance' 底下），資料庫沒辦法
-- 針對「陣列裡的某一筆」做權限判斷。
--
-- 現在「非管理員只能打自己的卡、只能看自己的紀錄」這條規則，
-- 是在前端程式碼（App.jsx）裡做判斷與畫面隱藏，屬於「應用層」的
-- 保護，不是資料庫強制擋下來的。對 5–20 人、彼此互相信任的小團隊
-- 內部工具來說，這樣通常已經足夠；但如果你之後在意「就算有人打開
-- 瀏覽器開發者工具，也不能改到別人的資料」這種更高等級的安全性，
-- 需要把各模組拆成真正的資料表（每個員工、每筆打卡各自一列），
-- 再針對每一列設 RLS 規則。這是之後可以再做的進階優化，非必要。
